### PR TITLE
Timezone

### PR DESCRIPTION
**Pull request by kanrin**
encode time.Time type can set timezone to encode to json string
default is normal local in time.Time.loc 
if local string is invalid, use the default location

### CODE REVIEW

**Comment by wI2L** [comment]
@kanrin `time.In` creates a copy of the time value, which would hurt encoding performances. I think the `time.Time` should be set to the proper timezone once and prior to encoding.

**Comment by kanrin** [comment]
I think, from the user's point of view, in some occasions, such as data read from other timezone, it is very convenient for users if it can be formatted into the time of the current timezone.
You want better encoding performances, I want better user experience.😄

**Comment by wI2L** [comment]
I understand your need, but there's no "formatting" about timezone. The timezone is a property of the `time.Value` per se, and as such, this kind of mutation by copy doesn't fit in an encoding library (and that's not only regarding performance). Changing the timezone should be handled by application's code instead, prior to encoding the `time.Time` value.

**Comment by kanrin** [comment]
Thank you for your answer

**Pull request closed without merging**
